#!/bin/bash
echo $(printf $PATH | tr ":" "\n" | wc -w)#!/bin/bash
echo $(printf $PATH | tr ":" "\n" | wc -w)#!/bin/bash
echo $(printf $PATH | tr ":" "\n" | wc -w)#!/bin/bash
echo $(printf $PATH | tr ":" "\n" | wc -w)#!/bin/bash
echo $(printf $PATH | tr ":" "\n" | wc -w)#!/bin/bash
echo $(printf $PATH | tr ":" "\n" | wc -w)#!/bin/bash
echo $(printf $PATH | tr ":" "\n" | wc -w)#!/bin/bash
echo $(printf $PATH | tr ":" "\n" | wc -w)#!/bin/bash
echo $(printf $PATH | tr ":" "\n" | wc -w)#!/bin/bash
echo $(printf $PATH | tr ":" "\n" | wc -w)#!/bin/bash
echo $(printf $PATH | tr ":" "\n" | wc -w)
