#!/usr/bin/env bash
# This bash script transfers a file from a client to server using scp

#if (("$#" < 4)); then
#    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
#    scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/;



file="$1"
ip="$2"
user="ubuntu"
key="~/.ssh/id_rsa"

if [ $# -eq 2 ]; then
	scp -i "$key" -o StrictHostKeyChecking=no "$path"/"$file" "$user"@"$ip":/home/"$user"/
else
	echo -e "Usage: ${brown}$filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY${reset}"
fi