#!/usr/bin/env bash
# This bash script transfers a file from a client to server using scp

# Assigning arguments to variables


if (("$#" < 4))
then
	echo "Usage: 0-transfer...."
else
	scp -0 "StrictHostKey" -i "$4" "$1" "$3"@"$2":~/
fi
