#!/usr/bin/env bash
# Install nginx on web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) 
# using curl, it must return a page that contains the string Hello World!

sudo apt-get -y update
sudo apt-get -y install nginx

#================================
# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
#cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
# Creating new index
# echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
#===============================
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
