#!/usr/bin/env bash
# Install nginx on your web-01 server
apt-get -y update
apt-get -y install nginx

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo sed -i "46i rewrite ^/redirect_me https://www.funminiyipeter.tech permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
