#!/usr/bin/env bash
# Install nginx on your web-01 server

# Updating Packages before performing installations
sudo apt -y update
sudo apt -y install nginx
sudo service nginx start

# Creating an index.html page
sudo echo "Hello World!" | sudo tee /var/www/html/index.html

# Creating a 404 Custom error page
sudo echo -e "Ceci n'est pas une page\n" | tee /var/www/html/404.html
sudo echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        location /redirect_me {
                return 301 https://www.funminiyipeter.tech;
        }

        location / {
                try_files \$uri \$uri/ =404;
        }

        error_page 404 /404.html;
        location = /404.html {
                root /var/www/html;
                internal;
        }
}" | sudo tee /etc/nginx/sites-enabled/default

sudo service nginx restart
