#!/usr/bin/env bash
# duplicate web-01 to web-02
# these scripts are an upgrade from the web-server scripts...

# uncomment to see the script run in action
#set -x


sudo apt -y update
sudo apt -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo echo 'Hello World!' | tee /var/www/html/index.html
sudo echo -e "Ceci n'est pas une page\n" | tee /var/www/html/404.html
sudo echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	add_header X-Served-By \$hostname;

	location /redirect_me {
			return 301 https://www.funminiyipeter.tech;
	}

	location / {
			try_files \$uri \$uri/ =404;
	}

	error_page 404 /404.html;
	location = /404.html {
			root /var/www/html;
			internal;
	}
}" | sudo tee /etc/nginx/sites-enabled/default

sudo service nginx restart

