#!/usr/bin/env bash
# duplicate web-01 to web-02
# these scripts are an upgrade from the web-server scripts...

# uncomment to see the script run in action
#set -x

apt-get -y update
apt-get -y install nginx
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo sed -i "/listen 80 default_server/a \\\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-available/default
sudo sed -i "46i rewrite ^/redirect_me https://www.funminiyipeter.tech permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
