#!/usr/bin/env bash
# duplicate web-01 to web-02
# these scripts are an upgrade from the web-server scripts...

# Install nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
    server_name _;
    location / {
        return 200 'Hello world';
    }
	location /redirect_me {
			return 301 https://www.funminiyipeter.tech;
	}
	
    location /redirected_page {
        return 200 'You have been redirected';
    }
    error_page 404 /404.html;
    location = /404.html {
        return 404 'Ceci n\'est pas une page';
    }
}" | sudo tee /etc/nginx/sites-available/default >/dev/null
sudo service nginx restart
echo "add_header X-Served-By \$hostname;" | sudo tee -a /etc/nginx/sites-available/default >/dev/null
sudo service nginx restart


