#!/usr/bin/env bash
# install load balancer

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install haproxy

echo "

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server 415321-web-01 18.207.1.251:80 check
    server 415321-web-02 54.87.234.134:80 check
" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart