#!/usr/bin/env bash
# configures a server to listening on port 80 of all servers active IPv4 IPs

# fix nginx listening on port 80
# cd to Nginx sites-enabled folder
cd /etc/nginx/sites-enabled/ || exit;
# Delete default file
rm default;
# Create symbolic link to the deafult file in sites-available
ln -s /etc/nginx/sites-available/default default;
# Restart Nginx
service nginx restart
