#!/usr/bin/env bash
# Start Apache so as to return a
# page conatining Hello Holberton

# Replace default index.html with custom page
echo "Hello Holberton" > /usr/local/apache2/htdocs/index.html

# Start Apache service
service apache2 start
