#!/usr/bin/env bash
# short and sweet fix with 7 lines long or
# less, cannot use ";", "&&" and "wget"

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
